# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in otel_snitch.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "cpu_time", github: "yfractal/cpu_time"