# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"
require 'rake/extensiontask'

RSpec::Core::RakeTask.new(:spec)

Rake::ExtensionTask.new(:otel_snitch) do |ext|
  ext.lib_dir = 'lib/otel_snitch'
end

task default: :compile
