dist:
  name: otelcol-snitch
  description: Otel Snitch Demo
  output_path: ./otelcol-dev
exporters:
  - gomod:
      # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
      go.opentelemetry.io/collector/exporter/debugexporter v0.115.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.115.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.115.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.115.0
  - gomod: snitch-receiver/snitchreceiver v0.0.1

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0

replaces:
  - snitch-receiver/snitchreceiver => ../snitchreceiver
